### ISSUE TITLE
Position and size of list items is wrong

### ISSUE THREAD

**Issue by Paul-creator** [Paul-creator/flutter_quill_to_pdf#2]
**Disclaimer:** It is possible that this bug is because of the [pdf library](https://pub.dev/packages/pdf) - In that case this issue would be closed,  just with the note, that it can't be solve in this repo.

<img width="1241" alt="Screenshot 2024-08-26 at 14 02 16" src="https://github.com/user-attachments/assets/a1a79c0d-dcb9-4767-abd0-6ac0416a7c1c">

I know that the [quill editors](https://github.com/singerdmx/flutter-quill) version isn't fully working in that regard either, but that is not important for this project. The pdf-creation is. 

### Tasks
- [ ] Make numbers resize according to font size
- [ ] Make bullets resize according to font size
- [ ] Make checkboxes resize according to font size
<img width="1027" alt="Screenshot 2024-08-26 at 14 14 00" src="https://github.com/user-attachments/assets/efdbeaf5-f307-494f-ad42-5b7cafdcbb7d">

### Not sure if this is already included in the tasks above
- [ ]  numbers - position according to font size
- [ ] bullets - position according to font size
- [ ] Check indeted lists
<img width="1054" alt="Screenshot 2024-08-26 at 14 10 58" src="https://github.com/user-attachments/assets/b1d540b5-8140-455e-a6f4-eba6c57968b2">
